stages:
  - test
  - deploy_develop

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/
    - node_modules/

test:
  stage: test
  tags:
    - docker-runner
  
  image:
    name: ghcr.io/jooyeshgar/freeamir-app:latest
    pull_policy: if-not-present
    entrypoint: [""] 
  
  services:
    - name: mariadb:11
      alias: mariadb
      pull_policy: if-not-present

  variables:
    MARIADB_DATABASE: testing_db
    MARIADB_ROOT_PASSWORD: root_password
    MYSQL_DATABASE: testing_db
    MYSQL_ROOT_PASSWORD: root_password
    DB_CONNECTION: mysql
    DB_HOST: mariadb
    DB_PORT: 3306
    DB_DATABASE: testing_db
    DB_USERNAME: root
    DB_PASSWORD: root_password

  before_script:
    - cp .env.ci .env
    - chmod -R 777 storage/ bootstrap/cache/
    - composer install --no-scripts --ignore-platform-reqs --no-interaction
    - php artisan migrate:fresh

  script:
    - php artisan test --colors=never


deploy_develop:
  stage: deploy_develop
  when: manual
  only:
    - main

  before_script: []
  after_script: []
  script:
    - ./vendor/bin/envoy run deploy