title: امیر
description: نرم‌افزار آزاد حسابداری لاراول برای کسب‌وکارهای ایرانی
app_url: "https://freeamir.ir"
layouts_dir: general/site/layouts

kramdown:
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
