title: امیر
description: نرم‌افزار آزاد حسابداری لاراول برای کسب‌وکارهای ایرانی
app_url: "https://freeamir.ir"
layouts_dir: general/site/layouts

exclude:
  - general/README.md
  - general/README.en.md

kramdown:
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
