<x-super-admin-layout :title="__('Dashboard')">
    <x-show-message-bags />

    @php
        $verificationRate = $metrics['users'] > 0 ? round(($metrics['verifiedUsers'] / $metrics['users']) * 100) : 0;
        $companyActivationRate = $metrics['newUsers'] > 0 ? $metrics['activationRate'] : 0;
        $verifiedNewUsers = min($metrics['newUsers'], (int) round($metrics['newUsers'] * ($verificationRate / 100)));
        $assignedNewUsers = min($verifiedNewUsers, (int) round($metrics['newUsers'] * ($companyActivationRate / 100)));
        $maxUserGrowth = max(1, $userGrowth->max('count'));
        $maxActivity = max(1, $activityTrend->max('count'));
        $kpis = [
            [__('New registrations'), $metrics['newUsers'], __('Last 30 days'), $metrics['userGrowthRate'], 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm7-3h6m-3-3v6', 'bg-[#16a394]/10 text-[#16a394]'],
            [__('Businesses'), $metrics['businesses'], __('Active: :count', ['count' => localizeNumber($metrics['activeBusinesses'])]), null, 'M3 21h18M6 21V7l6-4 6 4v14M9 10h1m4 0h1', 'bg-indigo-50 text-indigo-500'],
            [__('Activation rate'), $metrics['activationRate'].'%', __('Company assigned'), null, 'M4 19V9m5 10V5m5 14v-7m5 7V3', 'bg-amber-50 text-amber-500'],
            [__('Monthly active users'), $metrics['monthlyActiveUsers'], __('MAU'), null, 'M3 12h4l3-9 4 18 3-9h4', 'bg-sky-50 text-sky-500'],
            [__('Churn rate'), $metrics['churnRate'].'%', __('Compared with prior period'), null, 'M4 6l6 6 4-4 6 6M4 18h16', 'bg-rose-50 text-[#f07662]'],
        ];
    @endphp

    @if ($metrics['unassignedUsers'] > 0)
        <div role="alert" class="mb-5 flex flex-col gap-3 rounded-xl border border-amber-200 bg-amber-50/80 p-4 text-xs text-amber-900 sm:flex-row sm:items-center">
            <span class="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-amber-100 font-bold text-amber-600">!</span>
            <p><b>{{ localizeNumber($metrics['unassignedUsers']) }}</b> {{ __('users have no company assignment.') }}</p>
            <a href="{{ route('users.index') }}" class="rounded-lg bg-white px-3 py-2 font-bold text-amber-700 shadow-sm sm:ms-auto">{{ __('Review users') }}</a>
        </div>
    @endif

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5" aria-label="{{ __('Platform metrics') }}">
        @foreach ($kpis as [$label, $value, $note, $change, $icon, $color])
            <article class="admin-rise rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
                <div class="flex items-start justify-between gap-3"><span class="{{ $color }} grid h-11 w-11 place-items-center rounded-xl"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="{{ $icon }}" /></svg></span>@if($change !== null)<span @class(['text-[10px] font-bold', 'text-emerald-600' => $change >= 0, 'text-rose-500' => $change < 0])>{{ $change >= 0 ? '↑' : '↓' }} {{ localizeNumber(abs($change)) }}٪</span>@endif</div>
                <p class="mt-5 text-xs text-slate-400">{{ $label }}</p><strong class="mt-1 block text-2xl font-extrabold text-[#15263b] dark:text-white">{{ localizeNumber(is_numeric($value) ? number_format($value) : $value) }}</strong><span class="mt-1 block text-[10px] text-slate-400">{{ $note }}</span>
            </article>
        @endforeach
    </section>

    <section class="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]">
        <article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6 dark:border-slate-800 dark:bg-slate-900">
            <header class="flex items-start justify-between gap-4"><div><h2 class="font-bold text-[#15263b] dark:text-white">{{ __('Growth and usage') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('New users during the last six months') }}</p></div><div class="text-end"><b class="block text-2xl text-[#16a394]">{{ localizeNumber(number_format($metrics['newUsers'])) }}</b><span class="text-[10px] text-slate-400">{{ __('Last 30 days') }}</span></div></header>
            <div class="mt-6 flex h-52 items-end gap-3 border-b border-slate-100 dark:border-slate-800" role="img" aria-label="{{ __('Monthly new-user trend') }}">@foreach($userGrowth as $month)<div class="flex h-full min-w-0 flex-1 flex-col justify-end gap-2 text-center"><span class="text-[10px] font-bold">{{ localizeNumber($month['count']) }}</span><div class="mx-auto w-full max-w-12 rounded-t-lg bg-[#16a394]" style="height: {{ max(4, round(($month['count'] / $maxUserGrowth) * 150)) }}px"></div><span class="pb-2 text-[10px] text-slate-400">{{ __($month['label']) }}</span></div>@endforeach</div>
        </article>
        <article class="grid-paper rounded-2xl bg-[#15263b] p-5 text-white shadow-lg sm:p-6">
            <header class="flex items-center justify-between"><div><h2 class="font-bold">{{ __('Active users') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Current platform engagement') }}</p></div><span class="rounded-lg bg-[#16a394]/15 px-2 py-1 text-[10px] font-bold text-emerald-300">DAU / WAU / MAU</span></header>
            <div class="mt-7 grid grid-cols-3 divide-x divide-x-reverse divide-white/10 text-center"><div><b class="block text-2xl">{{ localizeNumber($metrics['dailyActiveUsers']) }}</b><span class="text-[10px] text-slate-400">DAU</span></div><div><b class="block text-2xl">{{ localizeNumber($metrics['weeklyActiveUsers']) }}</b><span class="text-[10px] text-slate-400">WAU</span></div><div><b class="block text-2xl">{{ localizeNumber($metrics['monthlyActiveUsers']) }}</b><span class="text-[10px] text-slate-400">MAU</span></div></div>
            <div class="mt-7 rounded-xl bg-white/5 p-4"><div class="flex justify-between text-xs"><span class="text-slate-400">{{ __('DAU/MAU stickiness') }}</span><b>{{ localizeNumber($metrics['monthlyActiveUsers'] > 0 ? round(($metrics['dailyActiveUsers'] / $metrics['monthlyActiveUsers']) * 100, 1) : 0) }}٪</b></div><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10"><div class="h-full rounded-full bg-[#16a394]" style="width: {{ $metrics['monthlyActiveUsers'] > 0 ? min(100, ($metrics['dailyActiveUsers'] / $metrics['monthlyActiveUsers']) * 100) : 0 }}%"></div></div></div>
        </article>
    </section>

    <section class="mt-5 grid gap-5 xl:grid-cols-[1.4fr_1fr]">
        <article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6 dark:border-slate-800 dark:bg-slate-900">
            <header class="flex items-start justify-between"><div><h2 class="font-bold">{{ __('Activation funnel') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('From registration to an assigned company') }}</p></div><div class="text-end"><b class="block text-2xl">{{ localizeNumber($companyActivationRate) }}٪</b><span class="text-[10px] text-slate-400">{{ __('Activation rate') }}</span></div></header>
            <div class="mt-7 grid gap-3 sm:grid-cols-4">@foreach([[__('Registration'),$metrics['newUsers'],100],[__('Email verification'),$verifiedNewUsers,$verificationRate],[__('Company assignment'),$assignedNewUsers,$companyActivationRate],[__('Monthly activity'),min($assignedNewUsers,$metrics['monthlyActiveUsers']),$metrics['newUsers'] > 0 ? round((min($assignedNewUsers,$metrics['monthlyActiveUsers'])/$metrics['newUsers'])*100) : 0]] as $step)<div class="rounded-xl border border-slate-100 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950/40"><div class="flex justify-between text-[10px]"><span>{{ $step[0] }}</span><span class="text-slate-400">{{ localizeNumber($step[2]) }}٪</span></div><b class="mt-2 block text-xl">{{ localizeNumber(number_format($step[1])) }}</b><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700"><div class="h-full rounded-full bg-[#16a394]" style="width: {{ min(100,$step[2]) }}%"></div></div></div>@endforeach</div>
        </article>
        <article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6 dark:border-slate-800 dark:bg-slate-900"><header><h2 class="font-bold">{{ __('Time to first value') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Operational readiness indicators') }}</p></header><div class="mt-8 text-center"><b class="text-4xl font-extrabold text-[#15263b] dark:text-white">{{ localizeNumber($metrics['activationRate']) }}٪</b><p class="mt-2 text-xs text-slate-400">{{ __('Users assigned to a company') }}</p></div><div class="mt-7 grid grid-cols-2 divide-x divide-x-reverse divide-slate-100 text-center"><div><b class="block text-lg">{{ localizeNumber($metrics['openFiscalYears']) }}</b><span class="text-[10px] text-slate-400">{{ __('Open fiscal years') }}</span></div><div><b class="block text-lg">{{ localizeNumber($metrics['verifiedUsers']) }}</b><span class="text-[10px] text-slate-400">{{ __('Verified users') }}</span></div></div></article>
    </section>

    <section class="mt-5 grid gap-5 xl:grid-cols-[1.2fr_1fr]">
        <article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6 dark:border-slate-800 dark:bg-slate-900"><header><h2 class="font-bold">{{ __('Engagement and retention') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Activity across key time windows') }}</p></header><div class="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">@foreach([['DAU',$metrics['dailyActiveUsers']],['WAU',$metrics['weeklyActiveUsers']],['MAU',$metrics['monthlyActiveUsers']],[__('Active businesses'),$metrics['activeBusinesses']]] as $item)<div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-950/40"><span class="text-[10px] text-slate-400">{{ $item[0] }}</span><b class="mt-1 block text-xl">{{ localizeNumber(number_format($item[1])) }}</b></div>@endforeach</div><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl border border-slate-100 p-4"><span class="text-[10px] text-slate-400">{{ __('DAU/MAU stickiness') }}</span><b class="mt-1 block text-lg">{{ localizeNumber($metrics['monthlyActiveUsers'] > 0 ? round(($metrics['dailyActiveUsers']/$metrics['monthlyActiveUsers'])*100,1) : 0) }}٪</b></div><div class="rounded-xl border border-slate-100 p-4"><span class="text-[10px] text-slate-400">{{ __('Documents this month') }}</span><b class="mt-1 block text-lg">{{ localizeNumber(number_format($metrics['monthlyDocuments'])) }}</b></div><div class="rounded-xl border border-rose-100 bg-rose-50/50 p-4"><span class="text-[10px] text-rose-500">{{ __('Churn rate') }}</span><b class="mt-1 block text-lg text-rose-600">{{ localizeNumber($metrics['churnRate']) }}٪</b></div></div></article>
        <article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm sm:p-6 dark:border-slate-800 dark:bg-slate-900"><header><h2 class="font-bold">{{ __('Retention cohort') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Activity volume over the last seven days') }}</p></header><div class="mt-6 grid grid-cols-7 gap-2">@foreach($activityTrend as $day)<div class="text-center"><div class="grid h-16 place-items-center rounded-lg bg-[#16a394] text-[10px] font-bold text-white" style="opacity: {{ max(.18,$day['count']/$maxActivity) }}">{{ localizeNumber($day['count']) }}</div><span class="mt-2 block text-[9px] text-slate-400">{{ __($day['label']) }}</span></div>@endforeach</div></article>
    </section>

    <section class="mt-5 grid gap-5 lg:grid-cols-3">
        <article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm lg:col-span-2 dark:border-slate-800 dark:bg-slate-900"><header class="flex items-center justify-between"><div><h2 class="font-bold">{{ __('Usage depth') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Accounting activity across the platform') }}</p></div><div class="text-end"><b class="text-lg">{{ localizeNumber($metrics['documentsPerActiveBusiness']) }}</b><span class="block text-[10px] text-slate-400">{{ __('Documents / active business') }}</span></div></header><div class="mt-5 grid gap-4 sm:grid-cols-3"><div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-950/40"><span class="text-[10px] text-slate-400">{{ __('Documents this month') }}</span><b class="mt-1 block text-2xl">{{ localizeNumber(number_format($metrics['monthlyDocuments'])) }}</b></div><div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-950/40"><span class="text-[10px] text-slate-400">{{ __('Invoices this month') }}</span><b class="mt-1 block text-2xl">{{ localizeNumber(number_format($metrics['monthlyInvoices'])) }}</b></div><div class="rounded-xl bg-slate-50 p-4 dark:bg-slate-950/40"><span class="text-[10px] text-slate-400">{{ __('Activity records') }}</span><b class="mt-1 block text-2xl">{{ localizeNumber(number_format($activityMetrics['total'])) }}</b></div></div></article>
        <article class="grid-paper rounded-2xl bg-[#15263b] p-5 text-white shadow-lg"><header class="flex items-center justify-between"><div><h2 class="font-bold">{{ __('System health') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Current application status') }}</p></div><span class="flex items-center gap-1.5 text-[10px] text-emerald-300"><i class="h-2 w-2 rounded-full bg-emerald-400"></i>{{ __('Stable') }}</span></header><div class="mt-5 space-y-3">@foreach([[__('Environment'),__(config('app.env'))],[__('Version'),localizeNumber(config('app.version'))],[__('Registration'),config('app.registration')?__('Enabled'):__('Disabled')],[__('Email verification'),config('app.email_verification')?__('Enabled'):__('Disabled')]] as $health)<div class="flex items-center justify-between rounded-xl bg-white/5 p-3"><span class="text-xs text-slate-300">{{ $health[0] }}</span><b class="text-sm">{{ $health[1] }}</b></div>@endforeach</div></article>
    </section>

    <section class="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]">
        <article class="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><header class="flex items-center justify-between border-b border-slate-100 p-5 sm:px-6 dark:border-slate-800"><div><h2 class="font-bold">{{ __('Latest fiscal years') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Recently added company records') }}</p></div><a href="{{ route('companies.index') }}" class="text-xs font-bold text-[#16a394]">{{ __('View all') }} ←</a></header><div class="scrollbar overflow-x-auto"><table class="table min-w-[620px]"><thead><tr><th>{{ __('Company') }}</th><th>{{ __('Fiscal year') }}</th><th>{{ __('Users') }}</th><th>{{ __('Status') }}</th><th></th></tr></thead><tbody>@forelse($recentCompanies as $company)<tr><td class="font-bold">{{ $company->name }}</td><td>{{ localizeNumber($company->fiscal_year) }}</td><td>{{ localizeNumber($company->users_count) }}</td><td><span @class(['rounded-full px-2.5 py-1 text-[10px]','bg-emerald-50 text-emerald-600'=>!$company->closed_at,'bg-slate-100 text-slate-500'=>$company->closed_at])>{{ $company->closed_at?__('Closed'):__('Open') }}</span></td><td><a href="{{ route('companies.edit',$company) }}" class="text-xs text-[#16a394]">{{ __('Edit') }}</a></td></tr>@empty<tr><td colspan="5" class="py-10 text-center">{{ __('No companies have been created yet.') }}</td></tr>@endforelse</tbody></table></div></article>
        <article class="rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><header class="border-b border-slate-100 p-5 dark:border-slate-800"><h2 class="font-bold">{{ __('Users by role') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Current access distribution') }}</p></header><div class="space-y-5 p-5">@forelse($roles as $role)@php($roleRate=$metrics['users']>0?min(100,round(($role->users_count/$metrics['users'])*100)):0)<div><div class="mb-2 flex justify-between text-xs"><span>{{ $role->name }}</span><b>{{ localizeNumber($role->users_count) }}</b></div><div class="h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div class="h-full rounded-full bg-[#16a394]" style="width:{{ $roleRate }}%"></div></div></div>@empty<p class="py-8 text-center text-xs text-slate-400">{{ __('No roles are configured.') }}</p>@endforelse<a href="{{ route('roles.index') }}" class="block rounded-xl border border-slate-200 px-3 py-2 text-center text-xs font-bold dark:border-slate-700">{{ __('Manage roles') }}</a></div></article>
    </section>

    <section class="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]">
        <article class="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><header class="flex items-center justify-between border-b border-slate-100 p-5 sm:px-6 dark:border-slate-800"><div><h2 class="font-bold">{{ __('New users') }}</h2><p class="mt-1 text-xs text-slate-400">{{ __('Newest platform accounts') }}</p></div><a href="{{ route('users.index') }}" class="text-xs font-bold text-[#16a394]">{{ __('View all') }} ←</a></header><div class="scrollbar overflow-x-auto"><table class="table min-w-[760px]"><thead><tr><th>{{ __('User') }}</th><th>{{ __('Role') }}</th><th>{{ __('Companies') }}</th><th>{{ __('Verification') }}</th><th></th></tr></thead><tbody>@forelse($recentUsers as $recentUser)<tr><td><a href="{{ route('users.show',$recentUser) }}" class="font-bold">{{ $recentUser->name }}</a><span class="block text-[10px] text-slate-400">{{ $recentUser->email }}</span></td><td>{{ $recentUser->roles->pluck('name')->join('، ') ?: __('No role') }}</td><td>{{ localizeNumber($recentUser->companies_count) }}</td><td><span @class(['rounded-full px-2.5 py-1 text-[10px]','bg-emerald-50 text-emerald-600'=>$recentUser->hasVerifiedEmail(),'bg-amber-50 text-amber-600'=>!$recentUser->hasVerifiedEmail()])>{{ $recentUser->hasVerifiedEmail()?__('Verified'):__('Pending') }}</span></td><td><div class="flex items-center justify-end gap-2">@unless($recentUser->hasVerifiedEmail())<form action="{{ route('users.verify',$recentUser) }}" method="post">@csrf<button class="text-[10px] text-emerald-600">{{ __('Verify') }}</button></form>@endunless @if(auth()->user()->canImpersonateUser($recentUser))<form action="{{ route('users.impersonate',$recentUser) }}" method="post">@csrf<button class="text-[10px] text-violet-600">{{ __('Impersonate') }}</button></form>@else<span class="text-[10px] text-slate-300" title="{{ (int)$recentUser->companies_count===0?__('User has no company'):__('Impersonation is not available for this user.') }}">{{ (int)$recentUser->companies_count===0?__('User has no company'):__('Impersonate') }}</span>@endif<a href="{{ route('users.edit',$recentUser) }}" class="text-[10px] text-[#16a394]">{{ __('Edit') }}</a></div></td></tr>@empty<tr><td colspan="5" class="py-10 text-center">{{ __('No users have been created yet.') }}</td></tr>@endforelse</tbody></table></div></article>
        <div class="space-y-5"><article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 class="font-bold">{{ __('Quick access') }}</h2><div class="mt-4 grid grid-cols-2 gap-3">@foreach([[__('Add user'),route('users.create'),'M12 5v14M5 12h14'],[__('Companies'),route('companies.index'),'M3 21h18M6 21V7l6-4 6 4v14'],[__('Access control'),route('roles.index'),'M12 3 4 7v5c0 5 3.4 8 8 9'],[__('Settings'),route('management.settings'),'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z']] as $action)<a href="{{ $action[1] }}" class="rounded-xl border border-slate-100 bg-slate-50 p-3 transition hover:border-[#16a394]/30 hover:bg-[#16a394]/5 dark:border-slate-800 dark:bg-slate-950/40"><span class="grid h-9 w-9 place-items-center rounded-lg bg-[#16a394]/10 text-[#16a394]"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-width="1.8" d="{{ $action[2] }}" /></svg></span><b class="mt-3 block text-xs">{{ $action[0] }}</b></a>@endforeach</div></article><article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex justify-between"><div><h2 class="font-bold">{{ __('Fiscal year status') }}</h2><p class="mt-1 text-[10px] text-slate-400">{{ __('Open and closed periods') }}</p></div><a href="{{ route('companies.index') }}" class="text-[10px] text-[#16a394]">{{ __('View all') }}</a></div><div class="mt-5 grid grid-cols-2 text-center"><div><b class="block text-xl">{{ localizeNumber($metrics['openFiscalYears']) }}</b><span class="text-[10px] text-slate-400">{{ __('Open') }}</span></div><div class="border-s border-slate-100"><b class="block text-xl">{{ localizeNumber($metrics['closedFiscalYears']) }}</b><span class="text-[10px] text-slate-400">{{ __('Closed') }}</span></div></div></article></div>
    </section>
</x-super-admin-layout>
